board/urls.py
from django.conf.urls import patterns, url
from board import views

uuidRegex = ''

urlpatterns = patterns('',
    url(r'^$', views.index, name='index'),
    url(r'^(?P<post_id>\d+)/$', views.get_post, name='get_post'),
    url(r'^post/$', views.make_post, name='make_post'),
    url(r'^file/(?P<file_name>[0-9a-fA-F]{8}[0-9a-fA-F]{4}[0-9a-f]{4}[0-9a-fA-F]{4}[0-9a-fA-F]{12}\.\w+)$', views.download_file, name='download_file')
)

chanchullo/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'chanchullo.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),

    url(r'^$', include('board.urls')),
    url(r'^board/', include('board.urls', namespace='board')),
    url(r'^admin/', include(admin.site.urls)),
)

board/models.py
from django.db import models

# Create your models here.
class Post(models.Model):
    title = models.CharField(max_length=200)
    content = models.CharField(max_length=400)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __unicode__(self):
        return self.title

class File(models.Model):
    post = models.ForeignKey(Post)
    path = models.CharField(max_length=200)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __unicode__(self):
        return self.path

class Comment(models.Model):
    post = models.ForeignKey(Post)
    content = models.CharField(max_length=400)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __unicode__(self):
        return self.content

class Tag(models.Model):
    post = models.ManyToManyField(Post)
    name = models.CharField(max_length=50)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __unicode__(self):
        return self.name

board/views.py
import os
import magic
from django.shortcuts import render
from django.http import HttpResponse, Http404, HttpResponseRedirect
from board.models import *
from board.utils import save_uploaded_file
import re
import json

def index(request):
    posts = Post.objects.order_by('-created_at')
    return render(request, 'posts/index.html', {
        'posts' : posts,
    })

def get_post(request, post_id):
    try:
        post = Post.objects.get(pk=post_id)
    except:
        raise Http404('Post no existe')

    return render(request, 'posts/detail.html', {
        'post' : post
    })

def make_post(request):
    try:
        title = request.POST['title']
        content = request.POST['content']
        if request.method == 'POST' and request.FILES:
            file_name = save_uploaded_file(request.FILES['file'])
        new_post = Post(title=title, content=content)
        new_post.save()

        new_file = File(path=file_name, post=new_post)
        new_file.save()
    except Exception as e:
        return HttpResponseRedirect('/error')

    return HttpResponseRedirect('/')

def download_file(request, file_name):
    path = '/home/donkeysharp/tmp/' + file_name
    if os.path.exists(path):
        response = HttpResponse()
        f = open(path)
        mime = magic.Magic(mime=True)
        response['Content-type'] = mime.from_file(path)
        response.content = f.read()
        f.close()

        return response
    else:
        raise Http404('Archivo no existe')

    new_post = Post(title=title, content=content)
    found_tags = re.findall('#\S*(?=\s)|#\S*(?=$)', content);
    registered_tags = []

    for tag in found_tags:
        if len(Tag.objects.all().filter(name=tag)) != 0:
            registered_tags.append(tag)

    new_post.save()

    return HttpResponse(json.dumps(registered_tags), content_type="application/json")

board/templates/posts/detail.html
<h1>{{post.title}}</h1>
<p>
    {{post.content}}
    <ul>
    {% for comment in post.comment_set.all %}
        <li>{{comment.content}}</li>
    {% endfor %}
    </ul>
</p>

board/templates/posts/index.html
{% load staticfiles %}
<link rel="stylesheet" type="text/css" href="{% static 'foundation/css/foundation.min.css' %}" />
<script src="{% static 'foundation/js/vendor/modernizr.js' %}"></script>



<div class="row">
  <div class="large-12 columns">
    <h1>Bienvenido a Chanchullo</h1>
  </div>
</div>

<div class="row">
  <div class="large-12 columns">
    <div class="panel">
        <h3>Compartir es bueno! (:</h3>
        <p>Aquí puedes compartir apuntes, exámenes pasados y cualquier cosa que se te ocurra.</p>
    </div>
  </div>
</div>

<div class="row">
    <div class="large-8 medium-8 columns">
        <h3>Postear algo</h3>
        <form action="{% url 'board:make_post' %}" method="POST" enctype="multipart/form-data">
            {% csrf_token %}
            <label for="title">Título</label>
            <input type="text" name="title" placeholder="Ejemplo: bale berga la bida" />
            <label for="content">Contenido</label>
            <textarea name="content" rows="5"></textarea>
            <input type="file" name="file" />
            <input type="submit" value="Postear" class="small button"/>
        </form>
    </div>
</div>

<br>

<div class="row">
    <div class="large-12 medium-8 columns">
        {% if posts %}
          {% for post in posts%}
            <div class="callout panel">
                <a href="/board/{{post.id}}">{{post.title}}</a>
                <p>{{post.content}}</p>
                {% if post.file_set.all %}
                    <a href="/board/file/{{post.file_set.all|first}}">Archivo adjunto</a>
                {% else %}
                {% endif %}
                <ul>
                {% for comment in post.comment_set.all %}
                    <li>{{comment.content}}</li>
                {% endfor %}
                </ul>
            </div>
          {% endfor %}
        {% endif%}
    </div>
</div>

<script src="{% static 'foundation/js/vendor/jquery.js' %}"></script>
<script src="{% static 'foundation/js/foundation.min.js' %}"></script>
<script>
  $(document).foundation();
</script>